// <auto-generated />
using System;
using DicePoker.Domain.AppDbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DicePoker.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230226132126_opponentHand")]
    partial class opponentHand
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DicePoker.Domain.Models.Hand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("NumberOfThrows")
                        .HasColumnType("int");

                    b.Property<string>("Numbers")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Hand");
                });

            modelBuilder.Entity("DicePoker.Domain.Models.HandPower", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("FollowingNumber")
                        .HasColumnType("int");

                    b.Property<int?>("HandId")
                        .HasColumnType("int");

                    b.Property<int>("LeadNumber")
                        .HasColumnType("int");

                    b.Property<int?>("OpponentHandId")
                        .HasColumnType("int");

                    b.Property<int>("handPowerType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("HandPower");
                });

            modelBuilder.Entity("DicePoker.Domain.Models.OpponentHand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("HandNumbers")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumberOfThrows")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("OpponentHand");
                });
#pragma warning restore 612, 618
        }
    }
}
